### ISSUE TITLE
egis0575

### ISSUE THREAD

**Issue by niclimcy** [indev29/egis0570#3]
This fingerprint should be quite similar.
https://gist.github.com/nicknitewolf/29e4320caede1e9a42240ca931cab926
Here are my results testing with pg/test:
Using:
```
#define DEV_PID 0x0575
#define DEV_EPOUT 0x01
#define DEV_EPIN 0x82
```

`min: 0 | max: 254 | avg: 78`
pgm image attached in gist above... It looks wrong...

**Comment by indev29** [comment]
I don't have access to this device and therefore can't test anything. I am aiming to get 0570 work first and data for other devices usually don't help.

Keep in mind, that similar Product IDs don't mean that devices work the same. They don't, that's exactly why these are different models. 

Anyways, I probably will work with other Egis sensors at some point, but there are some problems with 0570 that are common for all Swift sensors. Basically, unless 0570 is working there won't be any progress with your device.
